### ISSUE TITLE
Thanks and suggestions

### ISSUE THREAD

**Issue by TheKiber** [n-a-t-e/xsd_download#2]
Hello guys!

1. First of all, thanks for this projectm it helps alot!

2. Unfortunately, it not work with https://docs-test.fss.ru/ws-insurer-crypto-v20_2/FileOperationsLnService?wsdl, because method url_to_path writes all schemas in to one file, named 'FileOperationsLnService'.

Example:
```
url: 'https://docs-test.fss.ru/ws-insurer-crypto-v20_2/FileOperationsLnService?xsd=../../xsd/v01/eln/WsSecurity.xsd', 
parsed: 'ParseResult(
    scheme='https', 
    netloc='docs-test.fss.ru', 
    path='/ws-insurer-crypto-v20_2/FileOperationsLnService', 
    params='', 
    query='xsd=../../xsd/v01/eln/WsSecurity.xsd', 
    fragment='')'
```
so, `url_to_path` is `'docs-test.fss.ru/ws-insurer-crypto-v20_2/FileOperationsLnService'`,
but must be something like that: `'docs-test.fss.ru/ws-insurer-crypto-v20_2/../../xsd/v01/eln/WsSecurity.xsd'`.

I have slightly modified code, and suggest it:
```python
def url_to_path(url: str) -> str:
    '''turns a URL to an XSD into a filesystem path
       eg "http://www.example.come/a/b/c.xsd" -> "./www.example.come/a/b/c.xsd"
    '''
    parsed = urlparse(url)
    path = parsed.netloc + parsed.path + parsed.query
    if parsed.query and "/" in parsed.query:
        path = path + parsed.query[parsed.query.rfind("/"):]
    return path
```

3. Also, `download_xml_url` does not work properly with unicode.
I suggest to simplize code, if its works on your test:
```python
def download_xml_url(url: str) -> str:
    'Fetches URL, returns text of the document'
    response = urllib.request.urlopen(url).read()
    return response.decode("utf-8")
```

4. And finally, `save_file` on windows used cp1251 encoding, but schemas in utf-8.
Patch this:
```python
def save_file(url: str, text: str) -> None:
    '''save the XSD `text` data to file path decided by `url`
       also creates the directory structure if it doesn't exist
    '''
    filename_complete = url_to_path(url)
    dir_name = os.path.dirname(XSD_DIR + '/' + filename_complete)

    # create directory structure
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)

    #     return last_path
    with open(XSD_DIR + '/' + filename_complete, "w", encoding="utf_8_sig") as f:
```

**Comment by n-a-t-e** [comment]
Hi, can you make this into a pull request so it's easier to see what changed?

**Comment by n-a-t-e** [comment]
Thanks, I will use some of these suggestions
